# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeekFit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeekFit
  pod 'GoogleMaps'
  pod 'RealmSwift'

  target 'GeekFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeekFitUITests' do
    # Pods for testing
  end

end
